import { PlanetData } from './types';

export const SOLAR_SYSTEM_DATA: PlanetData[] = [
  {
    id: 'sun',
    name: 'Sun',
    type: 'Star',
    description: 'The star at the center of our Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core.',
    color: '#facc15',
    radius: 4,
    distance: 0,
    speed: 0,
    details: {
      radius: '696,340 km',
      mass: '1.989 × 10^30 kg',
      gravity: '274 m/s²',
      dayLength: '25 Earth days',
      orbitalPeriod: 'N/A',
      temperature: '5,500°C (Surface)',
      moons: 0,
      atmosphere: 'Hydrogen, Helium',
    },
  },
  {
    id: 'mercury',
    name: 'Mercury',
    type: 'Terrestrial Planet',
    description: 'The smallest planet in the Solar System and the closest to the Sun. Its orbit around the Sun takes 87.97 Earth days, the shortest of all the Sun\'s planets.',
    color: '#9ca3af',
    radius: 0.8,
    distance: 8,
    speed: 0.04,
    details: {
      radius: '2,439.7 km',
      mass: '3.285 × 10^23 kg',
      gravity: '3.7 m/s²',
      dayLength: '59 Earth days',
      orbitalPeriod: '88 days',
      temperature: '-180°C to 430°C',
      moons: 0,
      atmosphere: 'Minimal (Oxygen, Sodium)',
    },
  },
  {
    id: 'venus',
    name: 'Venus',
    type: 'Terrestrial Planet',
    description: 'The second planet from the Sun. It is named after the Roman goddess of love and beauty. As the brightest natural object in Earth\'s night sky after the Moon.',
    color: '#e5e7eb',
    radius: 1.1,
    distance: 12,
    speed: 0.03,
    details: {
      radius: '6,051.8 km',
      mass: '4.867 × 10^24 kg',
      gravity: '8.87 m/s²',
      dayLength: '243 Earth days',
      orbitalPeriod: '225 days',
      temperature: '462°C',
      moons: 0,
      atmosphere: 'Carbon Dioxide, Nitrogen',
    },
  },
  {
    id: 'earth',
    name: 'Earth',
    type: 'Terrestrial Planet',
    description: 'Our home planet. It is the third planet from the Sun and the only astronomical object known to harbor life.',
    color: '#3b82f6',
    radius: 1.2,
    distance: 16,
    speed: 0.02,
    details: {
      radius: '6,371 km',
      mass: '5.972 × 10^24 kg',
      gravity: '9.807 m/s²',
      dayLength: '24 hours',
      orbitalPeriod: '365.25 days',
      temperature: '-88°C to 58°C',
      moons: 1,
      atmosphere: 'Nitrogen, Oxygen',
    },
  },
  {
    id: 'mars',
    name: 'Mars',
    type: 'Terrestrial Planet',
    description: 'The fourth planet from the Sun and the second-smallest planet. It is often referred to as the "Red Planet" due to the effect of the iron oxide prevalent on Mars\'s surface.',
    color: '#ef4444',
    radius: 0.9,
    distance: 22,
    speed: 0.015,
    details: {
      radius: '3,389.5 km',
      mass: '6.39 × 10^23 kg',
      gravity: '3.71 m/s²',
      dayLength: '24h 37m',
      orbitalPeriod: '687 days',
      temperature: '-140°C to 20°C',
      moons: 2,
      atmosphere: 'Carbon Dioxide',
    },
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    type: 'Gas Giant',
    description: 'The fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass one-thousandth that of the Sun, but two-and-a-half times that of all the other planets combined.',
    color: '#d97706',
    radius: 2.8,
    distance: 32,
    speed: 0.008,
    details: {
      radius: '69,911 km',
      mass: '1.898 × 10^27 kg',
      gravity: '24.79 m/s²',
      dayLength: '9h 56m',
      orbitalPeriod: '12 years',
      temperature: '-108°C',
      moons: 79,
      atmosphere: 'Hydrogen, Helium',
    },
  },
  {
    id: 'saturn',
    name: 'Saturn',
    type: 'Gas Giant',
    description: 'The sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is a gas giant with an average radius of about nine and a half times that of Earth.',
    color: '#fcd34d',
    radius: 2.4,
    distance: 42,
    speed: 0.006,
    details: {
      radius: '58,232 km',
      mass: '5.683 × 10^26 kg',
      gravity: '10.44 m/s²',
      dayLength: '10h 42m',
      orbitalPeriod: '29 years',
      temperature: '-139°C',
      moons: 82,
      atmosphere: 'Hydrogen, Helium',
    },
  },
  {
    id: 'uranus',
    name: 'Uranus',
    type: 'Ice Giant',
    description: 'The seventh planet from the Sun. Its name is a reference to the Greek god of the sky, Uranus. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System.',
    color: '#22d3ee',
    radius: 1.8,
    distance: 52,
    speed: 0.004,
    details: {
      radius: '25,362 km',
      mass: '8.681 × 10^25 kg',
      gravity: '8.69 m/s²',
      dayLength: '17h 14m',
      orbitalPeriod: '84 years',
      temperature: '-197°C',
      moons: 27,
      atmosphere: 'Hydrogen, Helium, Methane',
    },
  },
  {
    id: 'neptune',
    name: 'Neptune',
    type: 'Ice Giant',
    description: 'The eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet.',
    color: '#3b82f6',
    radius: 1.7,
    distance: 62,
    speed: 0.003,
    details: {
      radius: '24,622 km',
      mass: '1.024 × 10^26 kg',
      gravity: '11.15 m/s²',
      dayLength: '16h 6m',
      orbitalPeriod: '165 years',
      temperature: '-201°C',
      moons: 14,
      atmosphere: 'Hydrogen, Helium, Methane',
    },
  },
];
